//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CupWorker {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class ProgSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ProgSettings defaultInstance = ((ProgSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ProgSettings())));
        
        public static ProgSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\SQLEXPRESS;Initial Catalog=kTVCSS;Integrated Security=SSPI;" +
            "")]
        public string SQL {
            get {
                return ((string)(this["SQL"]));
            }
            set {
                this["SQL"] = value;
            }
        }
    }
}
