USE [master]
GO

/****** Object:  Database [kTVCSS]    Script Date: 06.12.2021 2:22:14 ******/
CREATE DATABASE [kTVCSS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'kTVCSS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\kTVCSS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'kTVCSS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\kTVCSS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [kTVCSS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [kTVCSS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [kTVCSS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [kTVCSS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [kTVCSS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [kTVCSS] SET ARITHABORT OFF 
GO

ALTER DATABASE [kTVCSS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [kTVCSS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [kTVCSS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [kTVCSS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [kTVCSS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [kTVCSS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [kTVCSS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [kTVCSS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [kTVCSS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [kTVCSS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [kTVCSS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [kTVCSS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [kTVCSS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [kTVCSS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [kTVCSS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [kTVCSS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [kTVCSS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [kTVCSS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [kTVCSS] SET  MULTI_USER 
GO

ALTER DATABASE [kTVCSS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [kTVCSS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [kTVCSS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [kTVCSS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [kTVCSS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [kTVCSS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [kTVCSS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [kTVCSS] SET  READ_WRITE 
GO


