USE [kTVCSS]
GO

/****** Object:  Table [dbo].[GameServers]    Script Date: 06.12.2021 2:24:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GameServers](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[HOST] [nvarchar](15) NOT NULL,
	[USERNAME] [nvarchar](20) NULL,
	[USERPASSWORD] [nvarchar](32) NULL,
	[PORT] [smallint] NULL,
	[GAMEPORT] [smallint] NOT NULL,
	[RCONPASSWORD] [nvarchar](32) NOT NULL,
	[ENABLED] [tinyint] NOT NULL,
	[BUSY] [tinyint] NOT NULL,
	[NODEHOST] [nvarchar](15) NOT NULL,
	[NODEPORT] [smallint] NOT NULL,
 CONSTRAINT [PK_GameServers] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


