USE [kTVCSS]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[InsertMatchBackupRecord] 
  @ID int,
  @STEAMID nvarchar(50),
  @MONEY int,
  @PW nvarchar(100),
  @SW nvarchar(100),
  @HE int,
  @FLASHBANGS int,
  @SMOKEGRENADES int,
  @HELM int,
  @ARMOR int,
  @DEFUSEKIT int,
  @FRAGS int,
  @DEATHS int
AS
BEGIN
	DECLARE @COUNT int

	SELECT @COUNT = COUNT(STEAMID) FROM [dbo].[MatchesBackups] WHERE STEAMID = @STEAMID AND ID = @ID

	IF (@COUNT = 0)
	BEGIN
		INSERT INTO [kTVCSS].[dbo].[MatchesBackups] 
		VALUES (@ID, @STEAMID, @MONEY, @PW, @SW, @HE, @FLASHBANGS, @SMOKEGRENADES, @HELM, @ARMOR, @DEFUSEKIT, @FRAGS, @DEATHS)
	END
	ELSE 
	BEGIN
		UPDATE [dbo].[MatchesBackups] SET MONEY = @MONEY, PRIMARYWEAPON = @PW, SECONDARYWEAPON = @SW, FRAGGRENADES = @HE, FLASHBANGS = @FLASHBANGS,
		SMOKEGRENADES = @SMOKEGRENADES, HELM = @HELM, ARMOR = @ARMOR, DEFUSEKIT = @DEFUSEKIT, FRAGS = @FRAGS, DEATHS = @DEATHS WHERE STEAMID = @STEAMID AND ID = @ID
	END
	
END