USE [kTVCSS]
GO

/****** Object:  Table [dbo].[MatchesLive]    Script Date: 08.12.2021 23:12:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MatchesLive](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ASCORE] [int] NOT NULL,
	[BSCORE] [int] NOT NULL,
	[SERVERID] [int] NOT NULL,
	[MAP] [nvarchar](20) NULL,
	[FINISHED] [tinyint] NOT NULL,
 CONSTRAINT [PK_MatchesLive] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


