USE [kTVCSS]
GO

/****** Object:  Table [dbo].[Matches]    Script Date: 06.12.2021 2:25:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Matches](
	[ID] [int] NOT NULL,
	[ANAME] [nvarchar](20) NOT NULL,
	[BNAME] [nvarchar](20) NOT NULL,
	[ASCORE] [int] NOT NULL,
	[BSCORE] [int] NOT NULL,
	[MATCHDATE] [datetime] NOT NULL,
	[MAP] [nvarchar](20) NOT NULL,
	[SERVERID] [int] NOT NULL,
 CONSTRAINT [PK_Matches] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


