USE [kTVCSS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MatchesBackups](
	[ID] [int] NOT NULL,
	[STEAMID] [nvarchar](50) NOT NULL,
	[MONEY] [nvarchar](10) NOT NULL,
	[PRIMARYWEAPON] [nvarchar](100) NOT NULL,
	[SECONDARYWEAPON] [nvarchar](100) NOT NULL,
	[FRAGGRENADES] [int] NOT NULL,
	[FLASHBANGS] [int] NOT NULL,
	[SMOKEGRENADES] [int] NOT NULL,
	[HELM] [int] NOT NULL,
	[ARMOR] [int] NOT NULL,
	[DEFUSEKIT] [int] NOT NULL,
	[FRAGS] [int] NOT NULL,
	[DEATHS] [int] NOT NULL
) ON [PRIMARY]
GO


