USE [kTVCSS]
GO

/****** Object:  StoredProcedure [dbo].[OnMatchHighlight]    Script Date: 22.02.2022 1:26:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[OnMatchHighlight] 
	@MATCHID int,
	@KILLS int,
	@OPENFRAG int,
	@STEAMID nvarchar(30)
AS
BEGIN
	DECLARE @COUNTHIGHLIGHTS int
	SELECT @COUNTHIGHLIGHTS = COUNT(STEAMID) FROM [dbo].[MatchesHighlights] WHERE STEAMID = @STEAMID AND ID = @MATCHID
	IF (@COUNTHIGHLIGHTS = 0)
	BEGIN
		INSERT INTO [dbo].[MatchesHighlights] (ID, STEAMID, TRIPPLES, QUADROS, RAMPAGES, OPENFRAGS) VALUES (@MATCHID, @STEAMID, 0, 0, 0, 0);
	END

	IF @OPENFRAG = 1
	BEGIN
		UPDATE [kTVCSS].[dbo].[MatchesHighlights] SET OPENFRAGS = OPENFRAGS + 1 WHERE STEAMID = @STEAMID AND ID = @MATCHID
	END

	IF @KILLS = 3
	BEGIN
		UPDATE [kTVCSS].[dbo].[MatchesHighlights] SET TRIPPLES = TRIPPLES + 1 WHERE STEAMID = @STEAMID AND ID = @MATCHID
	END
	IF @KILLS = 4
	BEGIN
		UPDATE [kTVCSS].[dbo].[MatchesHighlights] SET QUADROS = QUADROS + 1 WHERE STEAMID = @STEAMID AND ID = @MATCHID
	END
	IF @KILLS = 5
	BEGIN
		UPDATE [kTVCSS].[dbo].[MatchesHighlights] SET RAMPAGES = RAMPAGES + 1 WHERE STEAMID = @STEAMID AND ID = @MATCHID
	END
END
GO


