SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE OnPlayerHighlight 
	@KILLS int,
	@STEAMID nvarchar(30)
AS
BEGIN
	IF @KILLS = 3
	BEGIN
	UPDATE [dbo].[PlayersHightlights] SET TRIPPLES = TRIPPLES + 1 WHERE STEAMID = @STEAMID
	END
	IF @KILLS = 4
	BEGIN
	UPDATE [dbo].[PlayersHightlights] SET QUADROS = QUADROS + 1 WHERE STEAMID = @STEAMID
	END
	IF @KILLS = 5
	BEGIN
	UPDATE [dbo].[PlayersHightlights] SET RAMPAGES = RAMPAGES + 1 WHERE STEAMID = @STEAMID
	END
END
GO
