USE [kTVCSS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[OnPlayerKill] 
	@KILLERNAME nvarchar(30),
	@KILLEDNAME nvarchar(30),
	@KILLERSTEAM nvarchar(30),
	@KILLEDSTEAM nvarchar(30),
	@KILLERHS tinyint,
	@SERVERID tinyint,
	@ID int
AS
BEGIN
	DECLARE @KILLEREXISTS tinyint;
	DECLARE @KILLEDEXISTS tinyint;
	SELECT @KILLEREXISTS = COUNT(@KILLERSTEAM) FROM [dbo].[MatchesResultsLive] WHERE ID = @ID;
	SELECT @KILLEDEXISTS = COUNT(@KILLEDSTEAM) FROM [dbo].[MatchesResultsLive] WHERE ID = @ID;

	IF (@KILLEREXISTS = 0)
	BEGIN
	INSERT INTO [dbo].[MatchesResultsLive] (STEAMID, KILLS, DEATHS, HEADSHOTS, SERVERID, ID) VALUES (@KILLERSTEAM, 0, 0, 0, @SERVERID, @ID);
	END

	IF (@KILLEDEXISTS = 0)
	BEGIN
	INSERT INTO [dbo].[MatchesResultsLive] (STEAMID, KILLS, DEATHS, HEADSHOTS, SERVERID, ID) VALUES (@KILLEDSTEAM, 0, 0, 0, @SERVERID, @ID);
	END

	UPDATE [dbo].[MatchesResultsLive] SET KILLS = 1 + KILLS, HEADSHOTS = @KILLERHS + HEADSHOTS WHERE STEAMID = @KILLERSTEAM AND ID = @ID;
	UPDATE [dbo].[MatchesResultsLive] SET DEATHS = 1 + DEATHS WHERE STEAMID = @KILLEDSTEAM AND ID = @ID;

	UPDATE [dbo].[Players] SET NAME = @KILLERNAME, KILLS = 1 + KILLS, HEADSHOTS = @KILLERHS + HEADSHOTS WHERE STEAMID = @KILLERSTEAM;
	UPDATE [dbo].[Players] SET NAME = @KILLEDNAME, DEATHS = 1 + DEATHS WHERE STEAMID = @KILLEDSTEAM;
END
GO


