SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE OnPlayerKillByWeapon
	@STEAMID nvarchar(30),
	@WEAPON nvarchar(50)
AS
BEGIN
	DECLARE @EXISTS int
	SELECT @EXISTS = COUNT(WEAPON) FROM [dbo].[PlayersWeaponKills] WHERE STEAMID = @STEAMID AND WEAPON = @WEAPON
	IF (@EXISTS = 0)
	BEGIN
		INSERT INTO kTVCSS.dbo.PlayersWeaponKills (STEAMID, WEAPON, COUNT) VALUES (@STEAMID, @WEAPON, 1)
	END
	ELSE 
	BEGIN
		UPDATE kTVCSS.dbo.PlayersWeaponKills SET COUNT = COUNT + 1 WHERE STEAMID = @STEAMID AND WEAPON = @WEAPON
	END
END
GO
