USE [kTVCSS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SetPlayerMatchResult]
	@STEAMID nvarchar(30),
	@WIN tinyint
AS
BEGIN
	DECLARE @CLB tinyint
	SELECT @CLB = ISCALIBRATION FROM [dbo].[Players] WHERE STEAMID = @STEAMID
	IF (@CLB = 1)
	BEGIN
		IF (@WIN = 1)
	BEGIN
		UPDATE [dbo].[Players] SET MATCHESPLAYED = MATCHESPLAYED + 1, MATCHESWINS = MATCHESWINS + 1, MMR = 0 WHERE STEAMID = @STEAMID
	END
	ELSE 
	BEGIN
		UPDATE [dbo].[Players] SET MATCHESPLAYED = MATCHESPLAYED + 1, MATCHESLOOSES = MATCHESLOOSES + 1, MMR = 0 WHERE STEAMID = @STEAMID
	END
	END
	ELSE
	BEGIN
	IF (@WIN = 1)
	BEGIN
		UPDATE [dbo].[Players] SET MATCHESPLAYED = MATCHESPLAYED + 1, MATCHESWINS = MATCHESWINS + 1, MMR = MMR + 25 WHERE STEAMID = @STEAMID
	END
	ELSE 
	BEGIN
		UPDATE [dbo].[Players] SET MATCHESPLAYED = MATCHESPLAYED + 1, MATCHESLOOSES = MATCHESLOOSES + 1, MMR = MMR - 25 WHERE STEAMID = @STEAMID
	END
	END
END
GO


