USE [kTVCSS]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SetPlayerMatchResult]
	@STEAMID nvarchar(30),
	@WIN tinyint
AS
BEGIN
	DECLARE @CLB tinyint
	DECLARE @MC int
	SELECT @CLB = ISCALIBRATION FROM [dbo].[Players] WHERE STEAMID = @STEAMID
	IF (@CLB = 1)
	BEGIN
		IF (@WIN = 1)
	BEGIN
		UPDATE [dbo].[Players] SET MATCHESPLAYED = MATCHESPLAYED + 1, MATCHESWINS = MATCHESWINS + 1, MMR = 0 WHERE STEAMID = @STEAMID
	END
	ELSE 
	BEGIN
		UPDATE [dbo].[Players] SET MATCHESPLAYED = MATCHESPLAYED + 1, MATCHESLOOSES = MATCHESLOOSES + 1, MMR = 0 WHERE STEAMID = @STEAMID
	END
	END
	ELSE
	BEGIN
	IF (@WIN = 1)
	BEGIN
		UPDATE [dbo].[Players] SET MATCHESPLAYED = MATCHESPLAYED + 1, MATCHESWINS = MATCHESWINS + 1, MMR = MMR + 25 WHERE STEAMID = @STEAMID
	END
	ELSE 
	BEGIN
		UPDATE [dbo].[Players] SET MATCHESPLAYED = MATCHESPLAYED + 1, MATCHESLOOSES = MATCHESLOOSES + 1, MMR = MMR - 25 WHERE STEAMID = @STEAMID
	END
	END
	UPDATE [dbo].[Players] SET LASTMATCH = SYSDATETIME() WHERE STEAMID = @STEAMID

	--Калибровка
	SELECT @MC = MATCHESPLAYED FROM [dbo].[Players] WHERE STEAMID = @STEAMID
	IF (@MC = 10)
	BEGIN
		DECLARE @PLAYERKILLS int
		DECLARE @PLAYERWINS int
		DECLARE @PLAYERHS int
		DECLARE @PLAYEROF int
		DECLARE @PLAYERTRIPPLES int
		DECLARE @PLAYERQUADROS int
		DECLARE @PLAYERRAMPAGES int
		DECLARE @PLAYERKD float

		SELECT @PLAYERKILLS = KILLS, @PLAYERWINS = MATCHESWINS, @PLAYERHS = HSR, @PLAYERKD = KDR FROM [dbo].[Players] WHERE STEAMID = @STEAMID
		SELECT @PLAYEROF = OPENFRAGS, @PLAYERTRIPPLES = TRIPPLES, @PLAYERQUADROS = QUADROS, @PLAYERRAMPAGES = RAMPAGES FROM [dbo].[PlayersHighlights] WHERE STEAMID = @STEAMID

		UPDATE [dbo].[Players] SET MMR = (100 * @PLAYERWINS) + (2 * @PLAYERKILLS) + (4 * @PLAYERHS) + 
		(@PLAYEROF) + (25 * @PLAYERTRIPPLES) + (50 * @PLAYERQUADROS) + (100 * @PLAYERRAMPAGES) + (300 * @PLAYERKD),
		ISCALIBRATION = 0 WHERE STEAMID = @STEAMID
	END

END
GO


